/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  storage721_code_id: number;
}
export type ExecuteMsg = {
  create_storage721: {
    collection_address: Addr;
    collection_code_id: number;
    is_original: boolean;
    label: string;
    owner: string;
    token_id: string;
  };
};
export type Addr = string;